### ISSUE TITLE
pickle data was truncated

### ISSUE THREAD

**Issue by lihuamei** [zhangbeibei-min/BertTCR#1]
您好，我们在使用BertTCR的时候，使用CPU载入模型，出现这个问题，是否是模型上传不完整导致的，期待您的回复。谢谢

Traceback (most recent call last):
  File "/home/Study/BertTCR/./Codes/BertTCR_prediction.py", line 145, in <module>
    sample = torch.load(sample_path)
  File "/root/miniconda3/envs/BertTCR/lib/python3.9/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/BertTCR/lib/python3.9/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: pickle data was truncated

**Comment by zhangbeibei-min** [comment]
我试了一下跑了这个BertTCR_prediction.py没出错，我重新上传了训练好的模型，可以再试一下

**Comment by amoschoomy** [comment]
Hello, I'm having the same issue as @lihuamei 


I've taken a look at your code:

```
# Predict samples.
    sample_dir = args.sample_dir if args.sample_dir[-1] == "/" else args.sample_dir + "/"
    with open(args.output, "w", encoding="utf8") as output_file:
        output_file.write("Sample\tProbability\tPrediction\n")
        for sample_file in os.listdir(sample_dir):
            # 构造样本文件路径
            sample_path = os.path.join(sample_dir, sample_file)
            # Read sample.
            sample = torch.load(sample_path)
            # 转换为指定设备上的 Tensor
            sample = sample.to(torch.device(args.device))

            # Generate input.
            input_matrix = sample

            # Make prediction.
            predict = model(input_matrix)
            prob = float(1 / (1 + math.exp(-predict[0][1] + predict[0][0])))
            pred = True if prob > 0.5 else False

            # Save result.
            output_file.write("{0}\t{1}\t{2}\n".format(sample_file, prob, pred))
    print("The prediction results have been saved to: " + args.output)
```

The sample path will be the TSV files provided, but here you are trying to `torch.load` the tsv file which will cause an pickle truncating error.

You will need to fix this code so the TSV files can be processed correctly as a dataset.

**Comment by zhangbeibei-min** [comment]
Hello, I understand that you are encountering an issue similar to @lihuamei. The problem arises because the code is attempting to use torch.load on TSV files, which is incorrect since torch.load is meant for loading .pth or .pt files, not TSV files. This results in a pickle truncating error.
To resolve this, you need to preprocess the TSV files using the BERT_embedding.py script to convert them into .pth files before you can use them for training or prediction.
